SELECT * FROM RUNDATA WHERE ACTIVITY_TYPE = 'WW5K';

INSERT INTO RUNDATA (DATE_SUBMITTED, ACTIVITY_TYPE) VALUES ('25-JUN-22', 'WW5K');

SELECT * FROM RUNDATA WHERE ACTIVITY_TYPE = 'Run' AND CALORIES_BURNED_KCAL > 350 ORDER BY DATE_SUBMITTED DESC, WORKOUT_DATE Desc;



CREATE TABLE race_tracker2
(race_number VARCHAR(24),
event VARCHAR(24),
event_date DATE,
distance FLOAT,
pace FLOAT);

INSERT INTO race_tracker2
(EVENT)
VALUES
('1');